doctrine:
    dbal:
        driver: pdo_mysql
        url: '%env(resolve:DATABASE_URL)%'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            AcmeSyliusRandomStickerPlugin:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'Acme\SyliusRandomStickerPlugin\Entity'
                alias: AcmeSyliusRandomStickerPlugin
