# Delete these routes and define your own shop routes here
RandomSticker_sylius_example_sticker_handler:
    path: /sticker-handler
    defaults:
        _controller: RandomSticker\SyliusStickerGeneratorPlugin\Controller\StickerController::handleStickerAction
        name: ~

RandomSticker_sylius_example_static_welcome:
    path: /static-welcome/{name}
    defaults:
        _controller: RandomSticker\SyliusStickerGeneratorPlugin\Controller\GreetingController::staticallyGreetAction
        name: ~

RandomSticker_sylius_example_dynamic_welcome:
    path: /dynamic-welcome/{name}
    defaults:
        _controller: RandomSticker\SyliusStickerGeneratorPlugin\Controller\GreetingController::dynamicallyGreetAction
        name: ~
